# Generated by Django 3.2.9 on 2021-11-02 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code of the currency')),
                ('from_currency_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the currency')),
                ('to_currency_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code of the currency')),
                ('to_currency_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the currency')),
                ('exchange_rate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exchange rate')),
                ('last_refreshed', models.DateTimeField(default=datetime.datetime.now, verbose_name='date and time of the last refresh')),
                ('time_zone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time zone')),
                ('bid_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bid price')),
                ('ask_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ask price')),
            ],
            options={
                'verbose_name': 'Rate',
                'ordering': ('last_refreshed',),
                'get_latest_by': ('last_refreshed',),
            },
        ),
    ]
